
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 14 01:45:27 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 27;
  public static final int CONTINUE = 25;
  public static final int ELSE = 22;
  public static final int CLASS = 5;
  public static final int IDENT = 9;
  public static final int RBRACE = 17;
  public static final int CHARACTER = 10;
  public static final int RETURN = 26;
  public static final int SEMI_COLON = 13;
  public static final int IF = 21;
  public static final int LBRACKET = 14;
  public static final int LBRACE = 16;
  public static final int RBRACKET = 15;
  public static final int PROGRAM = 2;
  public static final int COMMA = 4;
  public static final int EOF = 0;
  public static final int NUMBER = 12;
  public static final int BREAK = 24;
  public static final int LPARENTHESIS = 18;
  public static final int RPARENTHESIS = 19;
  public static final int PRINT = 28;
  public static final int CONST = 3;
  public static final int error = 1;
  public static final int ASSIGN = 8;
  public static final int ABSTRACT = 7;
  public static final int BOOL = 11;
  public static final int FOR = 23;
  public static final int EXTENDS = 6;
  public static final int VOID = 20;
}

