
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Feb 02 15:07:35 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 36;
  public static final int LBRACKET = 16;
  public static final int GREATER_OR_EQUAL = 43;
  public static final int INCREMENT = 31;
  public static final int CONST = 3;
  public static final int EQUALS = 40;
  public static final int GREATER = 42;
  public static final int CONTINUE = 27;
  public static final int LESS = 44;
  public static final int FOR = 25;
  public static final int MINUS = 12;
  public static final int DECREMENT = 32;
  public static final int CHARACTER = 10;
  public static final int AND = 34;
  public static final int LESS_OR_EQUAL = 45;
  public static final int OR = 33;
  public static final int BOOL = 11;
  public static final int COMMA = 4;
  public static final int CLASS = 5;
  public static final int MULTIPLY = 35;
  public static final int PLUS = 13;
  public static final int ASSIGN = 8;
  public static final int IF = 23;
  public static final int ABSTRACT = 7;
  public static final int EOF = 0;
  public static final int RETURN = 28;
  public static final int RBRACKET = 17;
  public static final int NEW = 38;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int SEMI_COLON = 15;
  public static final int MOD = 37;
  public static final int LPARENTHESIS = 20;
  public static final int NUMBER = 14;
  public static final int BREAK = 26;
  public static final int IDENT = 9;
  public static final int VOID = 22;
  public static final int COLON = 39;
  public static final int LBRACE = 18;
  public static final int ELSE = 24;
  public static final int READ = 29;
  public static final int DIFFERS = 41;
  public static final int RPARENTHESIS = 21;
  public static final int RBRACE = 19;
  public static final int EXTENDS = 6;
  public static final int PRINT = 30;
}

